# Generated by Django 5.0.7 on 2024-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_remove_urldb_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldb',
            name='code',
            field=models.TextField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='urldb',
            name='longurl',
            field=models.URLField(),
        ),
    ]
